CREATE DATABASE NETFLIX_DATA;

SELECT * FROM netflix;

-- question 1. Countries and their subscription types
SELECT 
    country,
    COUNT(CASE WHEN subscription_type = 'basic' THEN 1 END) AS basic_count,
    COUNT(CASE WHEN subscription_type = 'standard' THEN 1 END) AS standard_count,
    COUNT(CASE WHEN subscription_type = 'premium' THEN 1 END) AS premium_count
FROM 
    netflix
GROUP BY 
    country;
    
    -- question 2. Subscription type and age bracket 
SELECT
    CASE
        WHEN age BETWEEN 26 AND 30 THEN '26-30'
        WHEN age BETWEEN 31 AND 40 THEN '31-40'
        WHEN age BETWEEN 41 AND 51 THEN '41-51'
        ELSE 'Unknown'
    END AS age_bracket,
    COUNT(CASE WHEN subscription_type = 'basic' THEN 1 END) AS basic_count,
    COUNT(CASE WHEN subscription_type = 'standard' THEN 1 END) AS standard_count,
    COUNT(CASE WHEN subscription_type = 'premium' THEN 1 END) AS premium_count
FROM
    netflix
GROUP BY
    age_bracket;
    
    -- question 3. Total revenue generated by subscription type
    SELECT
    subscription_type,
    SUM(monthly_revenue) AS total_monthly_revenue
FROM
    netflix
GROUP BY
    subscription_type;
    
    -- question 4. Device and age bracket 
    SELECT
    CASE
        WHEN age BETWEEN 26 AND 30 THEN '26-30'
        WHEN age BETWEEN 31 AND 40 THEN '31-40'
        WHEN age BETWEEN 41 AND 51 THEN '41-51'
        ELSE 'Unknown'
    END AS age_bracket,
     COUNT(CASE WHEN device = 'laptop' THEN 1 END) AS laptop_count,
    COUNT(CASE WHEN device = 'smartphone' THEN 1 END) AS smartphone_count,
    COUNT(CASE WHEN device = 'tablet' THEN 1 END) AS tablet_count,
    COUNT(CASE WHEN device = 'SMART TV' THEN 1 END) AS tv_count
FROM
    netflix
GROUP BY
    age_bracket;

    
    
    


